services:
- type: web
  name: ecu-backend
  runtime: python
  repo: https://github.com/patompong1984/ecu-backend
  plan: free
  region: oregon
  buildCommand: pip install -r requirements.txt
  startCommand: python main.py
  autoDeployTrigger: commit
version: "1"
